version: '3'
services:
  envoy:
    image: envoyproxy/envoy-dev:43cd7847892892a0be3f01e2c7e8189bfb0a6321
    ports:
      - "10000:10000"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ../../../_cert/ca.cert:/etc/envoy/certs/ca.crt