apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hub-ingress
  namespace: hub
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`pulse.localhost`) && PathPrefix(`/hub`)
      services:
        - name: hub
          port: 8000