version: '3'

services:
  postgres:
    image: pulse-postgres
    build: .
    environment:
      - "POSTGRES_MULTIPLE_DATABASES=pulse"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"