version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./conf:/etc/redis/